version: '3'

services:

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: esquenta-nest-api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    build: .docker/postgres
    container_name: esquenta-nest-api-db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=nest_api
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_USER=root

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.container_name
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:9000"
    depends_on:
     - db